# Generated by Django 5.1 on 2024-08-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leeds',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
