# Generated by Django 5.1 on 2024-08-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leeds',
            name='status',
            field=models.CharField(choices=[('uncalled', 'Uncalled'), ('called', 'Called'), ('recalled', 'Recalled'), ('complete', 'Complete'), ('rejected', 'Rejected')], default='uncalled', max_length=50),
        ),
    ]
