# Generated by Django 5.1 on 2024-08-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_leeds_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leeds',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
